version: '3'
services:
  app:
    restart: always
    build: .
    container_name: IPFS-Upload-Relay
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - MODE=prod
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
      - FOREVERLAND_BUCKET=xxx
